//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.Status = "Active";
        }
    
        public int AdminID { get; set; }
        public string Password_MD5 { get; set; }
        public string AdminName { get; set; }
        public string Contact { get; set; }
        public string Sex { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
    }
}
