//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Recommendation
    {
        public int ID { get; set; }
        public int BookID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime Add_Time { get; set; }
        public int Status { get; set; }
        public string Location { get; set; }
        public System.DateTime Create_Time { get; set; }
        public Nullable<int> Update_user { get; set; }
        public System.DateTime Update_Time { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
