//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_favorite
    {
        public int ID { get; set; }
        public int PublisherID { get; set; }
        public int BookID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
